export const project = {
  name: 'project',
  title: 'Project',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'year',
      title: 'Year',
      type: 'string',
    },
    {
      name: 'image',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
    },
    {
      name: 'description',
      title: 'Short Description',
      type: 'text',
      rows: 3,
    },
    {
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    },
    {
      name: 'featured',
      title: 'Featured on home page',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'sortOrder',
      title: 'Sort order',
      description: 'Lower numbers appear first. Leave blank to fall back to year (newest first). Use gaps of 10 (10, 20, 30…) so you can slot new items in without renumbering.',
      type: 'number',
    },
    {
      name: 'publishedAt',
      title: 'Published on',
      description: 'The real publication date. Search engines and AI answer engines both weight recency, and they need a date — not just a year.',
      type: 'datetime',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'updatedAt',
      title: 'Last meaningfully updated',
      description: 'Leave blank unless you revise the piece. Used for dateModified.',
      type: 'datetime',
    },
    {
      name: 'seoDescription',
      title: 'Search description',
      description: 'The snippet shown in search results. Falls back to the short description if blank. Aim for 140–160 characters.',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.max(160).warning('Google truncates past about 160 characters.'),
    },
    {
      name: 'body',
      title: 'Body',
      type: 'portableBody',
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'year', media: 'image' },
  },
}
